### ISSUE TITLE
TODO/FIXME Count 4

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/http-signature-header#21]
- [ ] TODO: get options from program env variables.
       Commit: (9b675c7) Clean up verify.
       File:  [bin/util.js:218](https://github.com/digitalbazaar/http-signature-header.git/blob/master/bin/util.js#L218)
       andrewjones commented a year ago

  - [ ] TODO: abstract middleware verify in this.
       Commit: (9b675c7) Clean up verify.
       File:  [bin/util.js:217](https://github.com/digitalbazaar/http-signature-header.git/blob/master/bin/util.js#L217)
       andrewjones commented a year ago

  - [ ] * TODO: factor out to new npm package.
       Commit: (931d47c) Abstract code to util file.
       File:  [bin/util.js:87](https://github.com/digitalbazaar/http-signature-header.git/blob/master/bin/util.js#L87)
       andrewjones commented a year ago

  - [ ] TODO implement verify
       Commit: (6bafa93) Update doc string.
       File:  [bin/http-signature-header-js:46](https://github.com/digitalbazaar/http-signature-header.git/blob/master/bin/http-signature-header-js#L46)
       andrewjones commented a year ago
